// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ee88ae567310fb13 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'ja'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * tint?: string // Tint
}} Props

 */
import { routes } from "./chunks/chunk-G7USPTQY.js";

// virtual:asd
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tKZPSL7dlyM9BqYhoTLD/Hw05H4c1OKJg9XDO68Be/Asd.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
import { motion } from "unframer";
function Asd(props) {
	const { tint } = props;
	return (
		<motion.div
			style={{
				margin: 50,
				width: 100,
				height: 100,
				borderRadius: 25,
				backgroundColor: tint,
			}}
			animate={{
				scale: 1.5,
			}}
			whileHover={{
				rotate: 90,
			}}
		/>
	);
}
addPropertyControls(Asd, {
	tint: {
		title: "Tint",
		type: ControlType.Color,
		defaultValue: "#09F",
	},
});

// virtual:asd
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "e4LsknX_i",
		name: "Japanese (Japan)",
		slug: "ja",
		code: "ja-JP",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			<Asd {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AsdFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={Asd}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, Asd);
var asd_default = ComponentWithRoot;
export { asd_default as default };
