// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ee88ae567310fb13 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'ja'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
}} Props

 */
import { Video } from "./chunks/chunk-6ZX3537U.js";
import "./chunks/chunk-VBFMUA7V.js";
import { routes } from "./chunks/chunk-G7USPTQY.js";

// virtual:hover-3
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1wdG6Fly2EJoDUqcIZcn/6BUBcTMwyhGQ91pP48bv/u0Fmtd2et.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	Image as Image1,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var VideoFonts = getFonts(Video);
var cycleOrder = ["tFskgOxWt", "FeCg5aiOe"];
var serializationHash = "framer-k0pKA";
var variantClassNames = {
	FeCg5aiOe: "framer-v-1y7h3gp",
	tFskgOxWt: "framer-v-1escl75",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "tFskgOxWt",
	"Variant 2": "FeCg5aiOe",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "tFskgOxWt",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "tFskgOxWt",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter135b6wa = activeVariantCallback(async (...args) => {
		setVariant("FeCg5aiOe");
	});
	const onMouseLeave47n3og = activeVariantCallback(async (...args) => {
		setVariant("tFskgOxWt");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1escl75",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"tFskgOxWt"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								FeCg5aiOe: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1tr6bwp"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"YlUo5oroQ"}
							onMouseEnter={onMouseEnter135b6wa}
							{...addPropertyOverrides(
								{
									FeCg5aiOe: {
										onMouseLeave: onMouseLeave47n3og,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<Image1
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 1080,
									intrinsicWidth: 2560,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											((componentViewport?.height || 304) *
												1 *
												0.42105263157894757 -
												Math.max(
													(componentViewport?.height || 304) * 1 * 1.4868,
													(componentViewport?.height || 304) * 1 * 0.3289,
												) /
													2),
									),
									pixelHeight: 1080,
									pixelWidth: 2560,
									sizes: `calc(${componentViewport?.width || "100vw"} * 1.0033)`,
									src: "https://framerusercontent.com/images/OU9FTXgpbwKZ9rxAao7sCJP7apI.png?width=2560&height=1080",
									srcSet:
										"https://framerusercontent.com/images/OU9FTXgpbwKZ9rxAao7sCJP7apI.png?scale-down-to=512&width=2560&height=1080 512w,https://framerusercontent.com/images/OU9FTXgpbwKZ9rxAao7sCJP7apI.png?scale-down-to=1024&width=2560&height=1080 1024w,https://framerusercontent.com/images/OU9FTXgpbwKZ9rxAao7sCJP7apI.png?scale-down-to=2048&width=2560&height=1080 2048w,https://framerusercontent.com/images/OU9FTXgpbwKZ9rxAao7sCJP7apI.png?width=2560&height=1080 2560w",
								}}
								className={"framer-154y2ta"}
								layoutDependency={layoutDependency}
								layoutId={"VGpK3MJcS"}
								style={{
									opacity: 1,
								}}
								variants={{
									FeCg5aiOe: {
										opacity: 0,
									},
								}}
							/>
						</motion.div>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-zkiltn-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"q0CHMVnd0-container"}
								nodeId={"q0CHMVnd0"}
								rendersWithMotion={true}
								scopeId={"u0Fmtd2et"}
							>
								<Video
									backgroundColor={"rgba(0, 0, 0, 0)"}
									borderRadius={0}
									bottomLeftRadius={0}
									bottomRightRadius={0}
									controls={false}
									height={"100%"}
									id={"q0CHMVnd0"}
									isMixedBorderRadius={false}
									layoutId={"q0CHMVnd0"}
									loop={true}
									muted={true}
									objectFit={"cover"}
									playing={false}
									poster={
										"https://framerusercontent.com/images/FfWkJSdm9rcNnQkJvH1PBuIGWdo.png?width=1920&height=1080"
									}
									posterEnabled={true}
									srcFile={
										"https://framerusercontent.com/assets/NAgFjN9g0dZy0BqrmY5xtQcVVU.mp4"
									}
									srcType={"Upload"}
									srcUrl={""}
									startTime={0}
									style={{
										height: "100%",
										width: "100%",
									}}
									topLeftRadius={0}
									topRightRadius={0}
									volume={25}
									width={"100%"}
									{...addPropertyOverrides(
										{
											FeCg5aiOe: {
												playing: true,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1rjsefk"}
							fonts={["GF;IBM Plex Mono-regular"]}
							layoutDependency={layoutDependency}
							layoutId={"kPUfNYaNK"}
							style={{
								"--extracted-gdpscs": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h1
									dir={"auto"}
									style={{
										"--font-selector": "R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
										"--framer-font-family": '"IBM Plex Mono", monospace',
										"--framer-font-open-type-features":
											"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
										"--framer-font-size": "36px",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.1em",
										"--framer-text-color":
											"var(--extracted-gdpscs, rgb(255, 255, 255))",
									}}
								>
									{"Feel (cover)"}
								</motion.h1>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1671p1l"}
							fonts={["GF;IBM Plex Mono-regular"]}
							layoutDependency={layoutDependency}
							layoutId={"giyzwTL7l"}
							style={{
								"--extracted-gdpscs": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h1
									dir={"auto"}
									style={{
										"--font-selector": "R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
										"--framer-font-family": '"IBM Plex Mono", monospace',
										"--framer-font-open-type-features":
											"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
										"--framer-font-size": "15px",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.1em",
										"--framer-text-color":
											"var(--extracted-gdpscs, rgb(255, 255, 255))",
									}}
								>
									{"Chrysalia Csilla"}
								</motion.h1>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-k0pKA.framer-rah4lj, .framer-k0pKA .framer-rah4lj { display: block; }",
	".framer-k0pKA.framer-1escl75 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 304px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; }",
	".framer-k0pKA .framer-1tr6bwp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-k0pKA .framer-154y2ta { flex: none; height: 149%; left: calc(49.83333333333336% - 100.33333333333334% / 2); min-height: 33%; position: absolute; top: calc(42.105263157894754% - max(32.89%, 148.6842105263158%) / 2); width: 100%; z-index: 1; }",
	".framer-k0pKA .framer-zkiltn-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	".framer-k0pKA .framer-1rjsefk { bottom: 6px; flex: none; height: auto; left: 6px; position: absolute; white-space: pre; width: auto; z-index: 1; }",
	".framer-k0pKA .framer-1671p1l { bottom: 46px; flex: none; height: auto; left: 9px; position: absolute; white-space: pre; width: auto; z-index: 1; }",
];
var Frameru0Fmtd2et = withCSS(Component, css, "framer-k0pKA");
var stdin_default = Frameru0Fmtd2et;
Frameru0Fmtd2et.displayName = "HOVER 3";
Frameru0Fmtd2et.defaultProps = {
	height: 304,
	width: 1200,
};
addPropertyControls(Frameru0Fmtd2et, {
	variant: {
		options: ["tFskgOxWt", "FeCg5aiOe"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Frameru0Fmtd2et,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "IBM Plex Mono",
					openType: true,
					source: "google",
					style: "normal",
					uiFamilyName: "IBM Plex Mono",
					url: "https://fonts.gstatic.com/s/ibmplexmono/v20/-F63fjptAgt5VM-kVkqdyU8n5i0g1l9kn-s.woff2",
					weight: "400",
				},
			],
		},
		...VideoFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hover-3
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "e4LsknX_i",
		name: "Japanese (Japan)",
		slug: "ja",
		code: "ja-JP",
	},
];
var defaultResponsiveVariants = {
	base: "tFskgOxWt",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Hover3FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var hover_3_default = ComponentWithRoot;
export { hover_3_default as default };
