// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ee88ae567310fb13 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'ja'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-G7USPTQY.js";

// virtual:jepang
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6ydukHb6PS74shfu5vr0/iE7LPjfiubaQbVWwnpfn/NZNp2Zh93.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["VPgPVnnmk", "dxLdxuOXe"];
var serializationHash = "framer-teq3Y";
var variantClassNames = {
	dxLdxuOXe: "framer-v-1eg1c4l",
	VPgPVnnmk: "framer-v-1cxm1ym",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "VPgPVnnmk",
	"Variant 2": "dxLdxuOXe",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "VPgPVnnmk",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "VPgPVnnmk",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapungm8d = activeVariantCallback(async (...args) => {
		setVariant("dxLdxuOXe");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "dxLdxuOXe") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1cxm1ym",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"VPgPVnnmk"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								dxLdxuOXe: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1mwgszn"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"HqTatbOoa"}
							onTap={onTapungm8d}
						>
							{isDisplayed() && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1izyea"}
									fonts={["GF;Boldonse-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"mdqYKS10r"}
									style={{
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "R0Y7Qm9sZG9uc2UtcmVndWxhcg==",
												"--framer-font-family": '"Boldonse", sans-serif',
												"--framer-font-size": "56px",
												"--framer-letter-spacing": "0.01em",
												"--framer-line-height": "3.3em",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(255, 255, 255))",
											}}
										>
											{"\u65E5\u672C\u8A9E"}
										</motion.p>
									</React.Fragment>
								</RichText>
							)}
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1ryrl4l"}
								fonts={["GF;Boldonse-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"d4IIkCp9k"}
								style={{
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7Qm9sZG9uc2UtcmVndWxhcg==",
											"--framer-font-family": '"Boldonse", sans-serif',
											"--framer-font-size": "56px",
											"--framer-letter-spacing": "0.01em",
											"--framer-line-height": "3.3em",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(255, 255, 255))",
										}}
									>
										{"WORKS"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-teq3Y.framer-rcxibm, .framer-teq3Y .framer-rcxibm { display: block; }",
	".framer-teq3Y.framer-1cxm1ym { height: 185px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 252px; }",
	".framer-teq3Y .framer-1mwgszn { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: -1px; overflow: visible; padding: 0px; position: absolute; top: -12px; width: min-content; }",
	".framer-teq3Y .framer-1izyea, .framer-teq3Y .framer-1ryrl4l { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
];
var FramerNZNp2Zh93 = withCSS(Component, css, "framer-teq3Y");
var stdin_default = FramerNZNp2Zh93;
FramerNZNp2Zh93.displayName = "jepang";
FramerNZNp2Zh93.defaultProps = {
	height: 185,
	width: 252,
};
addPropertyControls(FramerNZNp2Zh93, {
	variant: {
		options: ["VPgPVnnmk", "dxLdxuOXe"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerNZNp2Zh93,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Boldonse",
					source: "google",
					style: "normal",
					uiFamilyName: "Boldonse",
					url: "https://fonts.gstatic.com/s/boldonse/v1/ZgNQjPxGPbbJUZemjC35hmHmNpCO.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:jepang
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "e4LsknX_i",
		name: "Japanese (Japan)",
		slug: "ja",
		code: "ja-JP",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders JepangFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var jepang_default = ComponentWithRoot;
export { jepang_default as default };
