// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ee88ae567310fb13 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'ja'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' | 'Phone Open' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-G7USPTQY.js";

// virtual:navigation
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/SX2Eg1FYCvu3oReJEMEp/jIT0YA9Rt1T9N9hZVD36/KBPnCS_6q.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/Jde9fbAt5euxEWtqTK0A/QtHVLXP59dgjCvlTVcQp/RpVBnQQl4.js
import { fontStore } from "unframer";
fontStore.loadFonts([]);
var fonts = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css = [
	".framer-l2Zz1 .framer-styles-preset-1yrj75n:not(.rich-text-wrapper), .framer-l2Zz1 .framer-styles-preset-1yrj75n.rich-text-wrapper a { --framer-link-text-color: #0099ff; }",
];
var className = "framer-l2Zz1";

// /:https://framerusercontent.com/modules/SX2Eg1FYCvu3oReJEMEp/jIT0YA9Rt1T9N9hZVD36/KBPnCS_6q.js
var cycleOrder = ["cxk_IxPPO", "yXsyfpLHT", "i6y7znHiA"];
var serializationHash = "framer-MY6FB";
var variantClassNames = {
	cxk_IxPPO: "framer-v-ofkwkv",
	i6y7znHiA: "framer-v-1y1g9iw",
	yXsyfpLHT: "framer-v-95h7ei",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Phone Open": "i6y7znHiA",
	Desktop: "cxk_IxPPO",
	Phone: "yXsyfpLHT",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "cxk_IxPPO",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "cxk_IxPPO",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapdlhb7j = activeVariantCallback(async (...args) => {
		setVariant("i6y7znHiA");
	});
	const onTap6zp15j = activeVariantCallback(async (...args) => {
		setVariant("yXsyfpLHT");
	});
	const onTapcmrr2s = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("cxk_IxPPO"), 1e3);
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["yXsyfpLHT", "i6y7znHiA"].includes(baseVariant)) return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.nav
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ofkwkv",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"cxk_IxPPO"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(0, 0, 0)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								i6y7znHiA: {
									"data-framer-name": "Phone Open",
								},
								yXsyfpLHT: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-6u2bpz"}
							data-framer-name={"Top"}
							layoutDependency={layoutDependency}
							layoutId={"OvvGC25y0"}
							{...addPropertyOverrides(
								{
									i6y7znHiA: {
										"data-highlight": true,
										onTap: onTap6zp15j,
									},
									yXsyfpLHT: {
										"data-highlight": true,
										onTap: onTapdlhb7j,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{isDisplayed() && (
								<motion.div
									className={"framer-1edusui"}
									data-framer-name={"Icon"}
									layoutDependency={layoutDependency}
									layoutId={"kqyYoiw7s"}
								>
									<motion.div
										className={"framer-1m60ze8"}
										data-framer-name={"Bottom"}
										layoutDependency={layoutDependency}
										layoutId={"Yeo9RfSgD"}
										style={{
											backgroundColor: "rgb(153, 153, 153)",
											borderBottomLeftRadius: 10,
											borderBottomRightRadius: 10,
											borderTopLeftRadius: 10,
											borderTopRightRadius: 10,
											rotate: 0,
										}}
										variants={{
											i6y7znHiA: {
												rotate: -45,
											},
										}}
									/>
									<motion.div
										className={"framer-xemvy0"}
										data-framer-name={"Top"}
										layoutDependency={layoutDependency}
										layoutId={"g5xpcvjjY"}
										style={{
											backgroundColor: "rgb(153, 153, 153)",
											borderBottomLeftRadius: 10,
											borderBottomRightRadius: 10,
											borderTopLeftRadius: 10,
											borderTopRightRadius: 10,
											rotate: 0,
										}}
										variants={{
											i6y7znHiA: {
												rotate: 45,
											},
										}}
									/>
								</motion.div>
							)}
						</motion.div>
						<motion.div
							className={"framer-1qme8d9"}
							data-framer-name={"Links"}
							layoutDependency={layoutDependency}
							layoutId={"BdvrPMXZt"}
							style={{
								opacity: 1,
							}}
							variants={{
								i6y7znHiA: {
									opacity: 1,
								},
								yXsyfpLHT: {
									opacity: 0,
								},
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-2enkxu"}
								data-highlight={true}
								fonts={["GF;Boldonse-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"DGUNmhkJt"}
								onTap={onTapcmrr2s}
								style={{
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										i6y7znHiA: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7SW50ZXIgVGlnaHQtNjAw",
															"--framer-font-family":
																'"Inter Tight", "Inter Tight Placeholder", sans-serif',
															"--framer-font-size": "32px",
															"--framer-font-weight": "600",
															"--framer-line-height": "1.5em",
															"--framer-text-alignment": "left",
														}}
													>
														<Link
															href={{
																hash: ":C0XJu4Y6A",
																webPageId: "augiA20Il",
															}}
															motionChild={true}
															nodeId={"DGUNmhkJt"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"KBPnCS_6q"}
															smoothScroll={true}
														>
															<motion.a
																className={"framer-styles-preset-1yrj75n"}
																data-styles-preset={"RpVBnQQl4"}
															>
																{"Works"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											),
											fonts: ["GF;Inter Tight-600"],
										},
										yXsyfpLHT: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7SW50ZXIgVGlnaHQtNjAw",
															"--framer-font-family":
																'"Inter Tight", "Inter Tight Placeholder", sans-serif',
															"--framer-font-size": "32px",
															"--framer-font-weight": "600",
															"--framer-line-height": "1.5em",
															"--framer-text-alignment": "left",
														}}
													>
														<Link
															href={{
																hash: ":C0XJu4Y6A",
																webPageId: "augiA20Il",
															}}
															motionChild={true}
															nodeId={"DGUNmhkJt"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"KBPnCS_6q"}
															smoothScroll={true}
														>
															<motion.a
																className={"framer-styles-preset-1yrj75n"}
																data-styles-preset={"RpVBnQQl4"}
															>
																{"Works"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											),
											fonts: ["GF;Inter Tight-600"],
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7Qm9sZG9uc2UtcmVndWxhcg==",
											"--framer-font-family": '"Boldonse", sans-serif',
											"--framer-font-size": "15px",
											"--framer-letter-spacing": "-0.01em",
											"--framer-line-height": "2em",
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(255, 255, 255))",
										}}
									>
										<Link
											href={{
												hash: ":C0XJu4Y6A",
												webPageId: "augiA20Il",
											}}
											motionChild={true}
											nodeId={"DGUNmhkJt"}
											openInNewTab={false}
											relValues={[]}
											scopeId={"KBPnCS_6q"}
											smoothScroll={true}
										>
											<motion.a
												className={"framer-styles-preset-1yrj75n"}
												data-styles-preset={"RpVBnQQl4"}
											>
												{"Works"}
											</motion.a>
										</Link>
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-9q3ywh"}
								fonts={["GF;Boldonse-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"a6T_N1O7y"}
								style={{
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										i6y7znHiA: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7SW50ZXIgVGlnaHQtNjAw",
															"--framer-font-family":
																'"Inter Tight", "Inter Tight Placeholder", sans-serif',
															"--framer-font-size": "32px",
															"--framer-font-weight": "600",
															"--framer-line-height": "1.5em",
															"--framer-text-alignment": "left",
														}}
													>
														<Link
															href={{
																hash: ":PveEnV2uf",
																webPageId: "augiA20Il",
															}}
															motionChild={true}
															nodeId={"a6T_N1O7y"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"KBPnCS_6q"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1yrj75n"}
																data-styles-preset={"RpVBnQQl4"}
															>
																{"About"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											),
											fonts: ["GF;Inter Tight-600"],
										},
										yXsyfpLHT: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7SW50ZXIgVGlnaHQtNjAw",
															"--framer-font-family":
																'"Inter Tight", "Inter Tight Placeholder", sans-serif',
															"--framer-font-size": "32px",
															"--framer-font-weight": "600",
															"--framer-line-height": "1.5em",
															"--framer-text-alignment": "left",
														}}
													>
														<Link
															href={{
																hash: ":PveEnV2uf",
																webPageId: "augiA20Il",
															}}
															motionChild={true}
															nodeId={"a6T_N1O7y"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"KBPnCS_6q"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1yrj75n"}
																data-styles-preset={"RpVBnQQl4"}
															>
																{"About"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											),
											fonts: ["GF;Inter Tight-600"],
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7Qm9sZG9uc2UtcmVndWxhcg==",
											"--framer-font-family": '"Boldonse", sans-serif',
											"--framer-font-size": "15px",
											"--framer-letter-spacing": "-0.2px",
											"--framer-line-height": "2em",
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(255, 255, 255))",
										}}
									>
										<Link
											href={{
												hash: ":PveEnV2uf",
												webPageId: "augiA20Il",
											}}
											motionChild={true}
											nodeId={"a6T_N1O7y"}
											openInNewTab={false}
											relValues={[]}
											scopeId={"KBPnCS_6q"}
											smoothScroll={false}
										>
											<motion.a
												className={"framer-styles-preset-1yrj75n"}
												data-styles-preset={"RpVBnQQl4"}
											>
												{"About"}
											</motion.a>
										</Link>
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1h87vw8"}
								fonts={["GF;Boldonse-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"Tn0MQLcWe"}
								style={{
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										i6y7znHiA: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7SW50ZXIgVGlnaHQtNjAw",
															"--framer-font-family":
																'"Inter Tight", "Inter Tight Placeholder", sans-serif',
															"--framer-font-size": "32px",
															"--framer-font-weight": "600",
															"--framer-line-height": "1.5em",
															"--framer-text-alignment": "left",
														}}
													>
														{"Contact"}
													</motion.p>
												</React.Fragment>
											),
											fonts: ["GF;Inter Tight-600"],
										},
										yXsyfpLHT: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7SW50ZXIgVGlnaHQtNjAw",
															"--framer-font-family":
																'"Inter Tight", "Inter Tight Placeholder", sans-serif',
															"--framer-font-size": "32px",
															"--framer-font-weight": "600",
															"--framer-line-height": "1.5em",
															"--framer-text-alignment": "left",
														}}
													>
														{"Contact"}
													</motion.p>
												</React.Fragment>
											),
											fonts: ["GF;Inter Tight-600"],
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7Qm9sZG9uc2UtcmVndWxhcg==",
											"--framer-font-family": '"Boldonse", sans-serif',
											"--framer-font-size": "15px",
											"--framer-letter-spacing": "-0.2px",
											"--framer-line-height": "2em",
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(255, 255, 255))",
										}}
									>
										{"Contact"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-879mam"}
							data-framer-name={"Bottom Line"}
							layoutDependency={layoutDependency}
							layoutId={"YniNsn0Rx"}
							style={{
								backgroundColor: "rgba(0, 0, 0, 0.08)",
							}}
						/>
					</motion.nav>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-MY6FB.framer-ahhq42, .framer-MY6FB .framer-ahhq42 { display: block; }",
	".framer-MY6FB.framer-ofkwkv { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: 64px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
	".framer-MY6FB .framer-6u2bpz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; min-height: 44px; min-width: 36px; overflow: visible; padding: 10px 0px 10px 10px; position: relative; width: min-content; }",
	".framer-MY6FB .framer-1edusui { flex: none; height: 40px; overflow: hidden; position: relative; width: 40px; }",
	".framer-MY6FB .framer-1m60ze8 { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(62.50000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); }",
	".framer-MY6FB .framer-xemvy0 { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(37.50000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); }",
	".framer-MY6FB .framer-1qme8d9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 276px; }",
	".framer-MY6FB .framer-2enkxu { -webkit-user-select: none; cursor: pointer; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-MY6FB .framer-9q3ywh, .framer-MY6FB .framer-1h87vw8 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-MY6FB .framer-879mam { bottom: 0px; flex: none; height: 1px; left: 0px; overflow: visible; position: absolute; right: 0px; z-index: 1; }",
	".framer-MY6FB.framer-v-95h7ei.framer-ofkwkv { flex-direction: column; gap: 0px; width: 390px; }",
	".framer-MY6FB.framer-v-95h7ei .framer-6u2bpz, .framer-MY6FB.framer-v-1y1g9iw .framer-6u2bpz { cursor: pointer; gap: unset; justify-content: space-between; min-height: unset; min-width: unset; padding: 10px; width: 100%; }",
	".framer-MY6FB.framer-v-95h7ei .framer-1edusui, .framer-MY6FB.framer-v-1y1g9iw .framer-1edusui { height: 44px; width: 44px; }",
	".framer-MY6FB.framer-v-95h7ei .framer-1qme8d9, .framer-MY6FB.framer-v-1y1g9iw .framer-1qme8d9 { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 0px; justify-content: flex-start; padding: 20px; width: 100%; }",
	".framer-MY6FB.framer-v-95h7ei .framer-2enkxu { order: 0; }",
	".framer-MY6FB.framer-v-95h7ei .framer-9q3ywh { order: 1; }",
	".framer-MY6FB.framer-v-95h7ei .framer-1h87vw8 { order: 2; }",
	".framer-MY6FB.framer-v-1y1g9iw.framer-ofkwkv { flex-direction: column; gap: 0px; height: min-content; max-height: calc(var(--framer-viewport-height, 100vh) * 1); overflow: auto; overscroll-behavior: contain; width: 390px; }",
	".framer-MY6FB.framer-v-1y1g9iw .framer-1m60ze8, .framer-MY6FB.framer-v-1y1g9iw .framer-xemvy0 { top: calc(50.00000000000002% - 2px / 2); }",
	...css,
];
var FramerKBPnCS_6q = withCSS(Component, css2, "framer-MY6FB");
var stdin_default = FramerKBPnCS_6q;
FramerKBPnCS_6q.displayName = "Navigation";
FramerKBPnCS_6q.defaultProps = {
	height: 64,
	width: 1200,
};
addPropertyControls(FramerKBPnCS_6q, {
	variant: {
		options: ["cxk_IxPPO", "yXsyfpLHT", "i6y7znHiA"],
		optionTitles: ["Desktop", "Phone", "Phone Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerKBPnCS_6q,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Boldonse",
					source: "google",
					style: "normal",
					uiFamilyName: "Boldonse",
					url: "https://fonts.gstatic.com/s/boldonse/v1/ZgNQjPxGPbbJUZemjC35hmHmNpCO.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter Tight",
					source: "google",
					style: "normal",
					uiFamilyName: "Inter Tight",
					url: "https://fonts.gstatic.com/s/intertight/v9/NGSnv5HMAFg6IuGlBNMjxJEL2VmU3NS7Z2mj0QiqWSRToK8EPg.woff2",
					weight: "600",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "e4LsknX_i",
		name: "Japanese (Japan)",
		slug: "ja",
		code: "ja-JP",
	},
];
var defaultResponsiveVariants = {
	base: "cxk_IxPPO",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavigationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var navigation_default = ComponentWithRoot;
export { navigation_default as default };
