// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ee88ae567310fb13 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'ja'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-S2H2IGCT.js";
import { routes } from "./chunks/chunk-G7USPTQY.js";

// virtual:njkkjh
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/HbOMuxUQD3PMNgENLOL7/AIcZOGiAMOcHtPvnniJB/A3933COPZ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var BahasaFonts = getFonts(stdin_default);
var cycleOrder = ["b5iTbd1Dj", "rIGnHUg37"];
var serializationHash = "framer-pjsGP";
var variantClassNames = {
	b5iTbd1Dj: "framer-v-10tlfiu",
	rIGnHUg37: "framer-v-i7qkxn",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "b5iTbd1Dj",
	"Variant 2": "rIGnHUg37",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "b5iTbd1Dj",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "b5iTbd1Dj",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTaps732cb = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("rIGnHUg37");
	});
	const F6iax4Dqocaz57w = activeVariantCallback(async (...args) => {
		setVariant("rIGnHUg37");
	});
	const NjUj1LdGy1haed1u = activeVariantCallback(async (...args) => {
		setVariant("b5iTbd1Dj");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-10tlfiu",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"b5iTbd1Dj"}
						onTap={onTaps732cb}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								rIGnHUg37: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1azqhe4"}
							fonts={["GF;Boldonse-regular"]}
							layoutDependency={layoutDependency}
							layoutId={"Etxx66SOm"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									rIGnHUg37: {
										children: (
											<React.Fragment>
												<motion.p
													style={{
														"--font-selector": "R0Y7Qm9sZG9uc2UtcmVndWxhcg==",
														"--framer-font-family": '"Boldonse", sans-serif',
														"--framer-font-size": "56px",
														"--framer-letter-spacing": "0.01em",
														"--framer-line-height": "3.3em",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(255, 255, 255))",
													}}
												>
													{"vbn"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "R0Y7Qm9sZG9uc2UtcmVndWxhcg==",
										"--framer-font-family": '"Boldonse", sans-serif',
										"--framer-font-size": "56px",
										"--framer-letter-spacing": "0.01em",
										"--framer-line-height": "3.3em",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"WORKS"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<ComponentViewportProvider
							height={30}
							width={"29px"}
							y={
								(componentViewport?.y || 0) +
								(0 + ((componentViewport?.height || 185) - 0 - 30) / 2)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1n0an3x-container"}
								layoutDependency={layoutDependency}
								layoutId={"tY1jUbfFZ-container"}
								nodeId={"tY1jUbfFZ"}
								rendersWithMotion={true}
								scopeId={"A3933COPZ"}
								style={{
									opacity: 0,
								}}
							>
								{_jsx(stdin_default, {
									F6iax4Dqo: F6iax4Dqocaz57w,
									height: "100%",
									id: "tY1jUbfFZ",
									layoutId: "tY1jUbfFZ",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "JUkFQFYOC",
									width: "100%",
									...addPropertyOverrides(
										{
											rIGnHUg37: {
												NjUj1LdGy: NjUj1LdGy1haed1u,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-pjsGP.framer-yobks4, .framer-pjsGP .framer-yobks4 { display: block; }",
	".framer-pjsGP.framer-10tlfiu { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 185px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 252px; }",
	".framer-pjsGP .framer-1azqhe4 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-pjsGP .framer-1n0an3x-container { flex: none; height: 30px; position: relative; width: 29px; }",
];
var FramerA3933COPZ = withCSS(Component, css, "framer-pjsGP");
var stdin_default2 = FramerA3933COPZ;
FramerA3933COPZ.displayName = "njkkjh";
FramerA3933COPZ.defaultProps = {
	height: 185,
	width: 252,
};
addPropertyControls(FramerA3933COPZ, {
	variant: {
		options: ["b5iTbd1Dj", "rIGnHUg37"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerA3933COPZ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Boldonse",
					source: "google",
					style: "normal",
					uiFamilyName: "Boldonse",
					url: "https://fonts.gstatic.com/s/boldonse/v1/ZgNQjPxGPbbJUZemjC35hmHmNpCO.woff2",
					weight: "400",
				},
			],
		},
		...BahasaFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:njkkjh
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "e4LsknX_i",
		name: "Japanese (Japan)",
		slug: "ja",
		code: "ja-JP",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NjkkjhFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var njkkjh_default = ComponentWithRoot;
export { njkkjh_default as default };
