// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ee88ae567310fb13 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'ja'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-G7USPTQY.js";

// virtual:pricelist
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1QArTFC0a0igvMjpfXuS/wsphMPTFwYUcpJxtrQy9/HfF5xz9_l.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-oDoDw";
var variantClassNames = {
	sUzG3kUXR: "framer-v-1a883ez",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "sUzG3kUXR",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1a883ez",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"sUzG3kUXR"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(0, 0, 0)",
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-ad1i8s"}
							fonts={["BI;ARK-ES/Dense Medium/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"TB7vZAiUd"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "Qkk7QVJLLUVTL0RlbnNlIE1lZGl1bS92MA==",
										"--framer-font-family": '"ARK-ES", sans-serif',
										"--framer-font-size": "29px",
										"--framer-letter-spacing": "-0.02em",
										"--framer-line-height": "1.21em",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"Simple"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1cfnik"}
							fonts={["GF;IBM Plex Mono-regular"]}
							layoutDependency={layoutDependency}
							layoutId={"GB_3z9glE"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
										"--framer-font-family": '"IBM Plex Mono", monospace',
										"--framer-font-size": "85px",
										"--framer-letter-spacing": "-0.02em",
										"--framer-line-height": "1.21em",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"Simple"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1u18mem"}
							fonts={["BI;ARK-ES/Dense Medium/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"fb3iG16ae"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "Qkk7QVJLLUVTL0RlbnNlIE1lZGl1bS92MA==",
										"--framer-font-family": '"ARK-ES", sans-serif',
										"--framer-font-size": "64px",
										"--framer-letter-spacing": "-0.02em",
										"--framer-line-height": "1.21em",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"70$/min"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-13557fr"}
							fonts={["GF;IBM Plex Mono-regular"]}
							layoutDependency={layoutDependency}
							layoutId={"tDB0d9LB1"}
							style={{
								"--extracted-1ok3k95": "rgb(255, 255, 255)",
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
										"--framer-font-family": '"IBM Plex Mono", monospace',
										"--framer-font-open-type-features":
											"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
										"--framer-font-size": "13px",
										"--framer-letter-spacing": "-0.02em",
										"--framer-line-height": "1.6em",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"Simple Text Motion Graphics"}
								</motion.p>
								<motion.ul
									style={{
										"--font-selector": "R0Y7SUJNIFBsZXggTW9uby1yZWd1bGFy",
										"--framer-font-family": '"IBM Plex Mono", monospace',
										"--framer-font-open-type-features":
											"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
										"--framer-font-size": "13px",
										"--framer-letter-spacing": "-0.02em",
										"--framer-line-height": "1.6em",
										"--framer-text-color":
											"var(--extracted-1ok3k95, rgb(255, 255, 255))",
									}}
								>
									<motion.li data-preset-tag={"p"}>
										<motion.p>{"Splendid color"}</motion.p>
									</motion.li>
									<motion.li data-preset-tag={"p"}>
										<motion.p>{"Majestic scene design"}</motion.p>
									</motion.li>
									<motion.li data-preset-tag={"p"}>
										<motion.p>{"Simple movement"}</motion.p>
									</motion.li>
								</motion.ul>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-oDoDw.framer-nbwrwk, .framer-oDoDw .framer-nbwrwk { display: block; }",
	".framer-oDoDw.framer-1a883ez { height: 301px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 507px; }",
	".framer-oDoDw .framer-ad1i8s { flex: none; height: 103px; position: absolute; right: -157px; top: 68px; white-space: pre-wrap; width: 296px; word-break: break-word; word-wrap: break-word; }",
	".framer-oDoDw .framer-1cfnik { flex: none; height: auto; left: -11px; position: absolute; top: -15px; white-space: pre; width: auto; }",
	".framer-oDoDw .framer-1u18mem { bottom: 9px; flex: none; height: auto; position: absolute; right: 20px; white-space: pre; width: auto; }",
	".framer-oDoDw .framer-13557fr { flex: none; height: 125px; left: 26px; position: absolute; top: 103px; white-space: pre-wrap; width: 337px; word-break: break-word; word-wrap: break-word; }",
];
var FramerHfF5xz9_l = withCSS(Component, css, "framer-oDoDw");
var stdin_default = FramerHfF5xz9_l;
FramerHfF5xz9_l.displayName = "pricelist";
FramerHfF5xz9_l.defaultProps = {
	height: 301,
	width: 507,
};
addFonts(
	FramerHfF5xz9_l,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "ARK-ES",
					source: "builtIn",
					style: "normal",
					uiFamilyName: "ARK-ES",
					url: "https://framerusercontent.com/assets/DLcoXUwNtNAUHS0aUZ1IjwvW90.woff",
					weight: "400",
				},
				{
					cssFamilyName: "IBM Plex Mono",
					openType: true,
					source: "google",
					style: "normal",
					uiFamilyName: "IBM Plex Mono",
					url: "https://fonts.gstatic.com/s/ibmplexmono/v20/-F63fjptAgt5VM-kVkqdyU8n5i0g1l9kn-s.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:pricelist
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "e4LsknX_i",
		name: "Japanese (Japan)",
		slug: "ja",
		code: "ja-JP",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PricelistFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var pricelist_default = ComponentWithRoot;
export { pricelist_default as default };
