// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ee88ae567310fb13 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'ja'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant-withtitle-hover-out' | 'Variant-withtitle-hover-in' // Variant
}} Props

 */
import {
	borderRadiusControl,
	defaultEvents,
	useIsBrowserSafari,
	useIsOnCanvas,
	useOnEnter,
	useOnExit,
	useRadius,
} from "./chunks/chunk-VBFMUA7V.js";
import { routes } from "./chunks/chunk-G7USPTQY.js";

// virtual:video-wrapper
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/CtbhCog1fZdzgOI7Qx7E/iToeEJjADw1DbuFoeEsY/UjZhXww2F.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/lRDHiNWNVWmE0lqtoVHP/qXQVWG1AZxpdrbBmhE1U/Video.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	useIsInCurrentNavigationTarget,
} from "unframer";
import { isMotionValue, useInView } from "unframer";
import { memo, useCallback, useEffect, useMemo, useRef, useState } from "react";
var ObjectFitType;
(function (ObjectFitType2) {
	ObjectFitType2["Fill"] = "fill";
	ObjectFitType2["Contain"] = "contain";
	ObjectFitType2["Cover"] = "cover";
	ObjectFitType2["None"] = "none";
	ObjectFitType2["ScaleDown"] = "scale-down";
})(ObjectFitType || (ObjectFitType = {}));
var SrcType;
(function (SrcType2) {
	SrcType2["Video"] = "Upload";
	SrcType2["Url"] = "URL";
})(SrcType || (SrcType = {}));
function getProps(props) {
	const {
		width,
		height,
		topLeft,
		topRight,
		bottomRight,
		bottomLeft,
		id,
		children,
		...rest
	} = props;
	return rest;
}
function Video(props) {
	const newProps = getProps(props);
	return <VideoMemo {...newProps} />;
}
function usePlaybackControls(videoRef) {
	const isInCurrentNavigationTarget = useIsInCurrentNavigationTarget();
	const requestingPlay = useRef(false);
	const setProgress = useCallback((rawProgress) => {
		if (!videoRef.current) return;
		const newProgress =
			(rawProgress === 1 ? 0.999 : rawProgress) * videoRef.current.duration;
		const isAlreadySet =
			Math.abs(videoRef.current.currentTime - newProgress) < 0.1;
		if (videoRef.current.duration > 0 && !isAlreadySet) {
			videoRef.current.currentTime = newProgress;
		}
	}, []);
	const play = useCallback(() => {
		const isPlaying =
			videoRef.current.currentTime > 0 &&
			videoRef.current.onplaying &&
			!videoRef.current.paused &&
			!videoRef.current.ended &&
			videoRef.current.readyState > videoRef.current.HAVE_CURRENT_DATA;
		if (
			!isPlaying &&
			videoRef.current &&
			!requestingPlay.current &&
			isInCurrentNavigationTarget
		) {
			requestingPlay.current = true;
			videoRef.current
				.play()
				.catch((e) => {})
				.finally(() => (requestingPlay.current = false));
		}
	}, []);
	const pause = useCallback(() => {
		if (!videoRef.current || requestingPlay.current) return;
		videoRef.current.pause();
	}, []);
	return {
		play,
		pause,
		setProgress,
	};
}
function useAutoplayBehavior({
	playingProp,
	muted,
	loop,
	playsinline,
	controls,
}) {
	const [initialPlayingProp] = useState(() => playingProp);
	const [hasPlayingPropChanged, setHasPlayingPropChanged] = useState(false);
	if (playingProp !== initialPlayingProp && !hasPlayingPropChanged) {
		setHasPlayingPropChanged(true);
	}
	const behavesAsGif =
		// passing `playing === true` on mount indicates that the video should
		// autoplay, like a GIF
		initialPlayingProp &&
		muted &&
		loop &&
		playsinline &&
		!controls &&
		// Some users of the <Video> component use it by wrapping it with
		// another smart component and adding their own controls on top. (The
		// controls use transitions to control the video: e.g., when clicking
		// the play button, the smart component will transition to a state with
		// <Video playing={true} />.) In this case, we don't want the video to
		// behave as a gif, as it will be weird if the video suddenly started
		// acting as such (and auto-pausing when leaving the viewport) as soon
		// as the site visitor mutes it and clicks “Play”.
		!hasPlayingPropChanged;
	let autoplay;
	if (behavesAsGif) autoplay = "on-viewport";
	else if (initialPlayingProp) autoplay = "on-mount";
	else autoplay = "no-autoplay";
	return autoplay;
}
var isMountedAndReadyForProgressChanges = false;
var VideoMemo = /* @__PURE__ */ memo(function VideoInner(props) {
	const {
		srcType,
		srcFile,
		srcUrl,
		playing: playingProp,
		muted,
		playsinline,
		controls,
		progress,
		objectFit,
		backgroundColor,
		onSeeked,
		onPause,
		onPlay,
		onEnd,
		onClick,
		onMouseEnter,
		onMouseLeave,
		onMouseDown,
		onMouseUp,
		poster,
		posterEnabled,
		startTime: startTimeProp,
		volume,
		loop,
	} = props;
	const videoRef = useRef();
	const isSafari = useIsBrowserSafari();
	const wasPausedOnLeave = useRef(null);
	const wasEndedOnLeave = useRef(null);
	const isOnCanvas = useIsOnCanvas();
	const borderRadius = useRadius(props);
	const autoplayBehavior = isOnCanvas
		? "no-autoplay"
		: useAutoplayBehavior({
				playingProp,
				muted,
				loop,
				playsinline,
				controls,
			});
	const isInViewport = isOnCanvas ? true : useInView(videoRef);
	const startTime = startTimeProp === 100 ? 99.9 : startTimeProp;
	const { play, pause, setProgress } = usePlaybackControls(videoRef);
	useEffect(() => {
		if (isOnCanvas) return;
		if (playingProp) play();
		else pause();
	}, [playingProp]);
	useEffect(() => {
		if (isOnCanvas) return;
		if (autoplayBehavior !== "on-viewport") return;
		if (isInViewport) play();
		else pause();
	}, [autoplayBehavior, isInViewport]);
	useEffect(() => {
		if (!isMountedAndReadyForProgressChanges) {
			isMountedAndReadyForProgressChanges = true;
			return;
		}
		const rawProgressValue = isMotionValue(progress)
			? progress.get()
			: (progress !== null && progress !== void 0 ? progress : 0) * 0.01;
		setProgress(
			// When the progress value exists (e.g. <Video startTime={10}
			// progress={50} />), we respect the `progress` value over
			// `startTime`, even if `startTime` changes. That’s because
			// `startTime` == start == changing it shouldn’t affect the current
			// progress
			(rawProgressValue !== null && rawProgressValue !== void 0
				? rawProgressValue
				: 0) ||
				// Then why fall back to `startTime` when `progress` doesn’t exist,
				// you might ask? Now, that’s for
				// - canvas UX: we want the video progress to change when the user
				//   is scrobbling the “Start Time” in component settings.
				// - backwards compatibility: maybe some users *are* scrobbling
				//   using `startTime` instead of `progress`? We don’t know, and it
				//   always supported it, so let’s not break it
				(startTime !== null && startTime !== void 0 ? startTime : 0) / 100,
		);
	}, [startTime, srcFile, srcUrl, progress]);
	useEffect(() => {
		if (!isMotionValue(progress)) return;
		return progress.on("change", (value) => setProgress(value));
	}, [progress]);
	useOnEnter(() => {
		if (wasPausedOnLeave.current === null) return;
		if (videoRef.current) {
			if ((!wasEndedOnLeave && loop) || !wasPausedOnLeave.current) play();
		}
	});
	useOnExit(() => {
		if (videoRef.current) {
			wasEndedOnLeave.current = videoRef.current.ended;
			wasPausedOnLeave.current = videoRef.current.paused;
			pause();
		}
	});
	const src = useMemo(() => {
		let fragment = "";
		if (srcType === SrcType.Url) return srcUrl + fragment;
		if (srcType === SrcType.Video) return srcFile + fragment;
	}, [srcType, srcFile, srcUrl, startTime]);
	useEffect(() => {
		if (isSafari && videoRef.current && autoplayBehavior === "on-mount") {
			setTimeout(() => play(), 50);
		}
	}, []);
	useEffect(() => {
		if (videoRef.current && !muted)
			videoRef.current.volume =
				(volume !== null && volume !== void 0 ? volume : 0) / 100;
	}, [volume]);
	const handleReady = () => {
		if (!videoRef.current) return;
		if (videoRef.current.currentTime < 0.3)
			setProgress(
				(startTime !== null && startTime !== void 0 ? startTime : 0) * 0.01,
			);
		if (autoplayBehavior === "on-mount") play();
	};
	return (
		<video
			onClick={onClick}
			onMouseEnter={onMouseEnter}
			onMouseLeave={onMouseLeave}
			onMouseDown={onMouseDown}
			onMouseUp={onMouseUp}
			src={src}
			loop={loop}
			ref={videoRef}
			onSeeked={(e) => {
				return onSeeked === null || onSeeked === void 0 ? void 0 : onSeeked(e);
			}}
			onPause={(e) => {
				return onPause === null || onPause === void 0 ? void 0 : onPause(e);
			}}
			onPlay={(e) => {
				return onPlay === null || onPlay === void 0 ? void 0 : onPlay(e);
			}}
			onEnded={(e) => {
				return onEnd === null || onEnd === void 0 ? void 0 : onEnd(e);
			}}
			autoPlay={autoplayBehavior === "on-mount"}
			poster={posterEnabled ? poster : void 0}
			onLoadedData={handleReady}
			controls={controls}
			muted={isOnCanvas ? true : muted}
			playsInline={playsinline}
			style={{
				cursor: !!onClick ? "pointer" : "auto",
				width: "100%",
				height: "100%",
				borderRadius,
				display: "block",
				objectFit,
				backgroundColor,
				objectPosition: "50% 50%",
			}}
		/>
	);
});
Video.displayName = "Video";
Video.defaultProps = {
	srcType: SrcType.Url,
	srcUrl:
		"https://assets.mixkit.co/videos/preview/mixkit-ice-cream-glass-of-red-soda-5094-small.mp4",
	srcFile: "",
	posterEnabled: false,
	controls: false,
	playing: true,
	loop: true,
	muted: true,
	playsinline: true,
	restartOnEnter: false,
	objectFit: ObjectFitType.Cover,
	backgroundColor: "rgba(0,0,0,0)",
	radius: 0,
	volume: 25,
	startTime: 0,
};
var groupsRegex = /[A-Z]{2,}|[A-Z][a-z]+|[a-z]+|[A-Z]|\d+/gu;
function capitalizeFirstLetter(value) {
	return value.charAt(0).toUpperCase() + value.slice(1);
}
function titleCase(value) {
	const groups = value.match(groupsRegex) || [];
	return groups.map(capitalizeFirstLetter).join(" ");
}
var objectFitOptions = [
	ObjectFitType.Cover,
	ObjectFitType.Fill,
	ObjectFitType.Contain,
	ObjectFitType.ScaleDown,
	ObjectFitType.None,
];
addPropertyControls(Video, {
	srcType: {
		type: ControlType.Enum,
		displaySegmentedControl: true,
		title: "Source",
		options: [SrcType.Url, SrcType.Video],
	},
	srcUrl: {
		type: ControlType.String,
		title: " ",
		placeholder: "../example.mp4",
		hidden(props) {
			return props.srcType === SrcType.Video;
		},
		description:
			"Hosted video file URL. For YouTube, use the YouTube component.",
	},
	srcFile: {
		type: ControlType.File,
		title: " ",
		allowedFileTypes: ["mp4"],
		hidden(props) {
			return props.srcType === SrcType.Url;
		},
	},
	playing: {
		type: ControlType.Boolean,
		title: "Playing",
		enabledTitle: "Yes",
		disabledTitle: "No",
	},
	posterEnabled: {
		type: ControlType.Boolean,
		title: "Poster",
		enabledTitle: "Yes",
		disabledTitle: "No",
	},
	poster: {
		type: ControlType.Image,
		title: " ",
		hidden: ({ posterEnabled }) => !posterEnabled,
	},
	backgroundColor: {
		type: ControlType.Color,
		title: "Background",
	},
	...borderRadiusControl,
	startTime: {
		title: "Start Time",
		type: ControlType.Number,
		min: 0,
		max: 100,
		step: 0.1,
		unit: "%",
	},
	loop: {
		type: ControlType.Boolean,
		title: "Loop",
		enabledTitle: "Yes",
		disabledTitle: "No",
	},
	objectFit: {
		type: ControlType.Enum,
		title: "Fit",
		options: objectFitOptions,
		optionTitles: objectFitOptions.map(titleCase),
	},
	// restartOnEnter: {
	//     type: ControlType.Boolean,
	//     title: "On ReEnter",
	//     enabledTitle: "Restart",
	//     disabledTitle: "Resume",
	// },
	controls: {
		type: ControlType.Boolean,
		title: "Controls",
		enabledTitle: "Show",
		disabledTitle: "Hide",
	},
	muted: {
		type: ControlType.Boolean,
		title: "Muted",
		enabledTitle: "Yes",
		disabledTitle: "No",
	},
	volume: {
		type: ControlType.Number,
		max: 100,
		min: 0,
		unit: "%",
		hidden: ({ muted }) => muted,
	},
	onEnd: {
		type: ControlType.EventHandler,
	},
	onSeeked: {
		type: ControlType.EventHandler,
	},
	onPause: {
		type: ControlType.EventHandler,
	},
	onPlay: {
		type: ControlType.EventHandler,
	},
	...defaultEvents,
});

// /:https://framerusercontent.com/modules/CtbhCog1fZdzgOI7Qx7E/iToeEJjADw1DbuFoeEsY/UjZhXww2F.js
var VideoFonts = getFonts(Video);
var cycleOrder = ["Sq163yNlw", "YRgfCtQEn"];
var serializationHash = "framer-YvZAJ";
var variantClassNames = {
	Sq163yNlw: "framer-v-17xtsz5",
	YRgfCtQEn: "framer-v-1ray8q6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant-withtitle-hover-in": "YRgfCtQEn",
	"Variant-withtitle-hover-out": "Sq163yNlw",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Sq163yNlw",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Sq163yNlw",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter1wnceyn = activeVariantCallback(async (...args) => {
		setVariant("YRgfCtQEn");
	});
	const onMouseLeave1l42vap = activeVariantCallback(async (...args) => {
		setVariant("Sq163yNlw");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-17xtsz5",
							className,
							classNames,
						)}
						data-framer-name={"Variant-withtitle-hover-out"}
						layoutDependency={layoutDependency}
						layoutId={"Sq163yNlw"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								YRgfCtQEn: {
									"data-framer-name": "Variant-withtitle-hover-in",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-11xrgu9-container"}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"ZbHckU7gu-container"}
								nodeId={"ZbHckU7gu"}
								rendersWithMotion={true}
								scopeId={"UjZhXww2F"}
							>
								<Video
									backgroundColor={"rgba(0, 0, 0, 0)"}
									borderRadius={0}
									bottomLeftRadius={0}
									bottomRightRadius={0}
									controls={false}
									height={"100%"}
									id={"ZbHckU7gu"}
									isMixedBorderRadius={false}
									layoutId={"ZbHckU7gu"}
									loop={true}
									muted={true}
									objectFit={"cover"}
									playing={false}
									posterEnabled={true}
									srcFile={
										"https://framerusercontent.com/assets/O48kuWd7EDdUBGIHtCnVQoxENU.mp4"
									}
									srcType={"Upload"}
									srcUrl={
										"https://videoframe.theanterior.in/pexels_videos_1093662+(1080p).mp4"
									}
									startTime={0}
									style={{
										height: "100%",
										width: "100%",
									}}
									topLeftRadius={0}
									topRightRadius={0}
									volume={25}
									width={"100%"}
									{...addPropertyOverrides(
										{
											YRgfCtQEn: {
												playing: true,
												startTime: 15,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-g4z4e0"}
							data-framer-name={"text-wrapper"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"cFvmme9Ug"}
							onMouseEnter={onMouseEnter1wnceyn}
							{...addPropertyOverrides(
								{
									YRgfCtQEn: {
										onMouseEnter: void 0,
										onMouseLeave: onMouseLeave1l42vap,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1ctxp5w"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"FRxRuHk17"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--framer-font-size": "29px",
										}}
									>
										{"Video"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-YvZAJ.framer-6weg1e, .framer-YvZAJ .framer-6weg1e { display: block; }",
	".framer-YvZAJ.framer-17xtsz5 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 556px; }",
	".framer-YvZAJ .framer-11xrgu9-container { flex: none; height: 400px; position: relative; width: 100%; }",
	".framer-YvZAJ .framer-g4z4e0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-YvZAJ .framer-1ctxp5w { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-YvZAJ.framer-v-1ray8q6 .framer-11xrgu9-container { order: 0; }",
	".framer-YvZAJ.framer-v-1ray8q6 .framer-g4z4e0 { order: 1; }",
];
var FramerUjZhXww2F = withCSS(Component, css, "framer-YvZAJ");
var stdin_default = FramerUjZhXww2F;
FramerUjZhXww2F.displayName = "video-wrapper";
FramerUjZhXww2F.defaultProps = {
	height: 445,
	width: 556,
};
addPropertyControls2(FramerUjZhXww2F, {
	variant: {
		options: ["Sq163yNlw", "YRgfCtQEn"],
		optionTitles: ["Variant-withtitle-hover-out", "Variant-withtitle-hover-in"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts(
	FramerUjZhXww2F,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...VideoFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:video-wrapper
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "e4LsknX_i",
		name: "Japanese (Japan)",
		slug: "ja",
		code: "ja-JP",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VideoWrapperFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var video_wrapper_default = ComponentWithRoot;
export { video_wrapper_default as default };
