// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ee88ae567310fb13 "Untitled", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'ja'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-G7USPTQY.js";

// virtual:works-jp
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/TdB4M9ezG8r8ML7vGj2c/vBNIvSsm81fFIPd5ltwQ/o7Xoo9EDZ.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["zXoeTXZx9", "ZmxTalvY1"];
var serializationHash = "framer-QL6Yt";
var variantClassNames = {
	ZmxTalvY1: "framer-v-kfec9r",
	zXoeTXZx9: "framer-v-1x7lo6h",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "zXoeTXZx9",
	"Variant 2": "ZmxTalvY1",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "zXoeTXZx9",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zXoeTXZx9",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1x7lo6h",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"zXoeTXZx9"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								ZmxTalvY1: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-qmn5h7"}
							layoutDependency={layoutDependency}
							layoutId={"u_SsMoStP"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-12okjdl"}
								fonts={["GF;Boldonse-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"ha4u57s4l"}
								style={{
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										ZmxTalvY1: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7Qm9sZG9uc2UtcmVndWxhcg==",
															"--framer-font-family": '"Boldonse", sans-serif',
															"--framer-font-size": "56px",
															"--framer-letter-spacing": "0.01em",
															"--framer-line-height": "3.3em",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														{"apa"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7Qm9sZG9uc2UtcmVndWxhcg==",
											"--framer-font-family": '"Boldonse", sans-serif',
											"--framer-font-size": "56px",
											"--framer-letter-spacing": "0.01em",
											"--framer-line-height": "3.3em",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(255, 255, 255))",
										}}
									>
										{"WORKS"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QL6Yt.framer-s14f2p, .framer-QL6Yt .framer-s14f2p { display: block; }",
	".framer-QL6Yt.framer-1x7lo6h { height: 185px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 252px; }",
	".framer-QL6Yt .framer-qmn5h7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: -1px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: absolute; top: -1px; width: min-content; }",
	".framer-QL6Yt .framer-12okjdl { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-QL6Yt.framer-v-kfec9r .framer-12okjdl { order: 0; }",
];
var Framero7Xoo9EDZ = withCSS(Component, css, "framer-QL6Yt");
var stdin_default = Framero7Xoo9EDZ;
Framero7Xoo9EDZ.displayName = "works jp";
Framero7Xoo9EDZ.defaultProps = {
	height: 185,
	width: 252,
};
addPropertyControls(Framero7Xoo9EDZ, {
	variant: {
		options: ["zXoeTXZx9", "ZmxTalvY1"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framero7Xoo9EDZ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Boldonse",
					source: "google",
					style: "normal",
					uiFamilyName: "Boldonse",
					url: "https://fonts.gstatic.com/s/boldonse/v1/ZgNQjPxGPbbJUZemjC35hmHmNpCO.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:works-jp
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "e4LsknX_i",
		name: "Japanese (Japan)",
		slug: "ja",
		code: "ja-JP",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders WorksJpFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ee88ae567310fb130215d686d6fd630589a152f6cbcc961db11fafd57bcee84a"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var works_jp_default = ComponentWithRoot;
export { works_jp_default as default };
